In [2]:
import yfinance as yf

In [ ]:
capital = 50000.00

In [17]:
with open("earnings.txt", "r") as f:
    data = [s.strip() for s in f.readlines()]

data_tuples = [el.split(":") for el in data]
data_tuples = [(spl[0].strip(), spl[1].strip()) for spl in data_tuples]
data_tuples.sort(key=lambda x: x[1])
print(data_tuples)

[('BE0003699130', '2023-11-20'), ('BE0003770840', '2023-11-20'), ('BE0003720340', '2023-11-20'), ('NL00150002Q7', '2023-11-20'), ('BE0003883031', '2023-11-21'), ('US67066G1040', '2023-11-21'), ('BE0003764785', '2023-11-23'), ('BE0003856730', '2023-11-23'), ('BE0003822393', '2023-11-24'), ('LU1789205884', '2023-11-28'), ('FR0005691656', '2023-11-28'), ('NL0013654783', '2023-11-29'), ('FR0000130395', '2023-11-30'), ('US79466L3024', '2023-11-30'), ('FR0000053324', '2023-12-05'), ('US36467W1099', '2023-12-05'), ('US11135F1012', '2023-12-06'), ('US7134481081', '2023-12-07'), ('BE0974256852', '2023-12-11'), ('US68389X1054', '2023-12-11'), ('US00724F1012', '2023-12-13'), ('US6541061031', '2023-12-18'), ('PA1436583006', '2023-12-19'), ('US9314271084', '2024-01-03'), ('NL0013654809', '2024-01-10'), ('US09247X1019', '2024-01-11'), ('US91324P1021', '2024-01-11'), ('US1729674242', '2024-01-12'), ('US46625H1005', '2024-01-12'), ('US38141G1040', '2024-01-16'), ('FR0000062796', '2024-01-16'), ('US64110L1061', '2024-01-17'), ('AN8068571086', '2024-01-18'), ('US88579Y1010', '2024-01-22'), ('US5949181045', '2024-01-22'), ('US75513E1010', '2024-01-22'), ('NL0000226223', '2024-01-22'), ('US8825081040', '2024-01-22'), ('US89417E1091', '2024-01-22'), ('US0028241000', '2024-01-23'), ('US00206R1023', '2024-01-23'), ('US0970231058', '2024-01-23'), ('US3696043013', '2024-01-23'), ('US4592001014', '2024-01-23'), ('US4781601046', '2024-01-23'), ('US7427181091', '2024-01-23'), ('IE00BKVD2N49', '2024-01-23'), ('US88160R1014', '2024-01-23'), ('US92343V1044', '2024-01-23'), ('NL0010273215', '2024-01-24'), ('US20030N1019', '2024-01-24'), ('US4581401001', '2024-01-24'), ('FR0000121014', '2024-01-24'), ('US57636Q1040', '2024-01-24'), ('US8447411088', '2024-01-24'), ('US92826C8394', '2024-01-24'), ('US0258161092', '2024-01-25'), ('US1667641005', '2024-01-25'), ('US1941621039', '2024-01-25'), ('US2605571031', '2024-01-25'), ('NL0011821392', '2024-01-25'), ('BE0003867844', '2024-01-26'), ('BE0974349814', '2024-01-26')]

In [6]:
with open("earnings22.txt", "r") as f:
    data = [s.strip() for s in f.readlines()]

data_tuples = [el.split(":") for el in data]
data_tuples = [(spl[0].strip(), spl[1].strip()) for spl in data_tuples]
data_tuples.sort(key=lambda x: x[1])

[('US88579Y1010', '2023-01-24'), ('US0028241000', '2023-01-25'), ('BE0003764785', '2022-11-23'), ('US00724F1012', '2022-12-15'), ('BE0003856730', '2022-11-24'), ('NL0010273215', '2023-01-25'), ('US00206R1023', '2023-01-25'), ('US09247X1019', '2023-01-13'), ('US0970231058', '2023-01-25'), ('FR0000063935', '2023-01-11'), ('US11135F1012', '2022-12-08'), ('PA1436583006', '2022-12-21'), ('US1729674242', '2023-01-13'), ('US20030N1019', '2023-01-26'), ('FR0000053324', '2022-12-06'), ('BE0974413453', '2022-11-22'), ('US36467W1099', '2022-12-07'), ('US3696043013', '2023-01-24'), ('US38141G1040', '2023-01-17'), ('US4592001014', '2023-01-25'), ('US4581401001', '2023-01-26'), ('US4781601046', '2023-01-24'), ('US57636Q1040', '2023-01-26'), ('US5949181045', '2023-01-24'), ('US64110L1061', '2023-01-19'), ('US6549022043', '2023-01-25'), ('US68389X1054', '2022-12-12'), ('FR0000120693', '2022-11-22'), ('US7427181091', '2023-01-19'), ('BE0003730448', '2023-01-26'), ('US75513E1010', '2023-01-24'), ('US79466L3024', '2022-11-30'), ('AN8068571086', '2023-01-20'), ('IE00BKVD2N49', '2023-01-25'), ('US8447411088', '2023-01-26'), ('NL0000226223', '2023-01-26'), ('US88160R1014', '2023-01-25'), ('US8825081040', '2023-01-24'), ('US89417E1091', '2023-01-24'), ('FR0005691656', '2023-01-04'), ('US91324P1021', '2023-01-13'), ('FR0013506730', '2022-11-21'), ('US92343V1044', '2023-01-24'), ('US92826C8394', '2023-01-26'), ('US9314271084', '2023-01-05')]
[('FR0013506730', '2022-11-21'), ('BE0974413453', '2022-11-22'), ('FR0000120693', '2022-11-22'), ('BE0003764785', '2022-11-23'), ('BE0003856730', '2022-11-24'), ('US79466L3024', '2022-11-30'), ('FR0000053324', '2022-12-06'), ('US36467W1099', '2022-12-07'), ('US11135F1012', '2022-12-08'), ('US68389X1054', '2022-12-12'), ('US00724F1012', '2022-12-15'), ('PA1436583006', '2022-12-21'), ('FR0005691656', '2023-01-04'), ('US9314271084', '2023-01-05'), ('FR0000063935', '2023-01-11'), ('US09247X1019', '2023-01-13'), ('US1729674242', '2023-01-13'), ('US91324P1021', '2023-01-13'), ('US38141G1040', '2023-01-17'), ('US64110L1061', '2023-01-19'), ('US7427181091', '2023-01-19'), ('AN8068571086', '2023-01-20'), ('US88579Y1010', '2023-01-24'), ('US3696043013', '2023-01-24'), ('US4781601046', '2023-01-24'), ('US5949181045', '2023-01-24'), ('US75513E1010', '2023-01-24'), ('US8825081040', '2023-01-24'), ('US89417E1091', '2023-01-24'), ('US92343V1044', '2023-01-24'), ('US0028241000', '2023-01-25'), ('NL0010273215', '2023-01-25'), ('US00206R1023', '2023-01-25'), ('US0970231058', '2023-01-25'), ('US4592001014', '2023-01-25'), ('US6549022043', '2023-01-25'), ('IE00BKVD2N49', '2023-01-25'), ('US88160R1014', '2023-01-25'), ('US20030N1019', '2023-01-26'), ('US4581401001', '2023-01-26'), ('US57636Q1040', '2023-01-26'), ('BE0003730448', '2023-01-26'), ('US8447411088', '2023-01-26'), ('NL0000226223', '2023-01-26'), ('US92826C8394', '2023-01-26')]

In [14]:
# US11135F1012: 2022-12-08

ticker = yf.Ticker("US11135F1012")
hist = ticker.history(start="2022-12-01", end="2022-12-15")
print(hist)

                                 Open        High         Low       Close  \
Date
2022-12-01 00:00:00-05:00  536.766616  538.120591  527.931386  536.493835
2022-12-02 00:00:00-05:00  523.148460  528.652234  522.203597  526.801392
2022-12-05 00:00:00-05:00  523.849802  525.515501  511.887642  516.904358
2022-12-06 00:00:00-05:00  516.914160  519.758559  508.244512  512.209167
2022-12-07 00:00:00-05:00  506.150116  511.410361  502.692020  505.078613
2022-12-08 00:00:00-05:00  507.328888  518.638350  506.910025  517.333069
2022-12-09 00:00:00-05:00  536.678961  538.334968  526.996255  530.619934
2022-12-12 00:00:00-05:00  530.649128  542.455397  528.204090  542.221619
2022-12-13 00:00:00-05:00  560.914904  566.779095  550.404225  556.258606
2022-12-14 00:00:00-05:00  553.833127  570.490530  553.034345  559.570679

                            Volume  Dividends  Stock Splits
Date
2022-12-01 00:00:00-05:00  2300600        0.0           0.0
2022-12-02 00:00:00-05:00  1932000        0.0           0.0
2022-12-05 00:00:00-05:00  1854800        0.0           0.0
2022-12-06 00:00:00-05:00  1965500        0.0           0.0
2022-12-07 00:00:00-05:00  1652400        0.0           0.0
2022-12-08 00:00:00-05:00  2751400        0.0           0.0
2022-12-09 00:00:00-05:00  3702800        0.0           0.0
2022-12-12 00:00:00-05:00  2341600        0.0           0.0
2022-12-13 00:00:00-05:00  4041400        0.0           0.0
2022-12-14 00:00:00-05:00  3521800        0.0           0.0

In [15]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-12-01 00:00:00-05:00,536.766616,538.120591,527.931386,536.493835,2300600,0.0,0.0
2022-12-02 00:00:00-05:00,523.148460,528.652234,522.203597,526.801392,1932000,0.0,0.0
2022-12-05 00:00:00-05:00,523.849802,525.515501,511.887642,516.904358,1854800,0.0,0.0
2022-12-06 00:00:00-05:00,516.914160,519.758559,508.244512,512.209167,1965500,0.0,0.0
2022-12-07 00:00:00-05:00,506.150116,511.410361,502.692020,505.078613,1652400,0.0,0.0
2022-12-08 00:00:00-05:00,507.328888,518.638350,506.910025,517.333069,2751400,0.0,0.0
2022-12-09 00:00:00-05:00,536.678961,538.334968,526.996255,530.619934,3702800,0.0,0.0
2022-12-12 00:00:00-05:00,530.649128,542.455397,528.204090,542.221619,2341600,0.0,0.0
2022-12-13 00:00:00-05:00,560.914904,566.779095,550.404225,556.258606,4041400,0.0,0.0
2022-12-14 00:00:00-05:00,553.833127,570.490530,553.034345,559.570679,3521800,0.0,0.0

In [11]:
import pandas as pd
from datetime import datetime as dt

print(dt.utcfromtimestamp(1249565400))


datetime = pd.to_datetime(1249565400)
print(datetime)

2009-08-06 13:30:00
1970-01-01 00:00:01.249565400